### Implementación de calsificador bayesiano usando el dataset iris

In [1]:
#Carga de bibliotecas
import numpy as np
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
data = load_iris().data
ntest = 0.2
nclass = 3

In [2]:
#Definición vectorial de la funcion de probabilidad Gaussiana
def gaussianPDF(x, m, s):
    res = (1/(np.sqrt(2*np.pi)*s)) * np.exp(-1 * pow((x-m),2) / (2*s) )
    l = x.shape[0]
    return res

In [3]:
#Entrenamiento
vs = []
means = []
for i in range(0, 3):
    index = np.arange(int((1-ntest)*i),int((i+1)*50))
    x = data[index]
    vs = np.append(vs, np.var(x,axis=0))
    means = np.append(means,np.mean(x,axis=0))
    
vs = vs.reshape([3,4])
means = means.reshape([3,4])
print("varianzas: \n{}".format(vs))
print("medias: \n{}".format(means))

varianzas: 
[[0.121764   0.142276   0.029504   0.011264  ]
 [0.407659   0.224364   2.077356   0.317475  ]
 [0.68196027 0.18666006 3.07559119 0.57567587]]
medias: 
[[5.006      3.418      1.464      0.244     ]
 [5.471      3.094      2.862      0.785     ]
 [5.84832215 3.05100671 3.77449664 1.20536913]]


In [4]:
def classifique(x, m, s):
    gpdf = gaussianPDF(x, m, s)
    l = m.shape[0]
    res = []
    for i in range(0,l):
        res = np.append(res,gpdf[i,0]*gpdf[i,1]*gpdf[i,2]*gpdf[i,3])
    return(np.argmax(res))

In [5]:
#Clasificacion de un patron aleatorio
y = load_iris().target[index]
rn = np.random.randint(low=0, high=150)
yy = load_iris().target[rn]
cls = classifique(data[rn], means, vs)
print("indece del patron a clasificar: {}".format(rn))
print("Patron a clasificar: {}".format(data[rn]))
print("Resultado esperado: {}".format(yy))
print("Salida del clasificador: {}".format(cls))

indece del patron a clasificar: 61
Patron a clasificar: [5.9 3.  4.2 1.5]
Resultado esperado: 1
Salida del clasificador: 2


In [6]:
#Resultados con conjunto de prueba: 0.3 (15xclase) , entrenamiento: 0.7 (35xclase)
index = np.concatenate([np.arange(50-int(ntest*50), 50), np.arange(100-int(ntest*50), 100), np.arange(150-int(ntest*50), 150)])
y = load_iris().target[index]
x = data[index]
l = x.shape[0]
predict = []
for i in range(0, l):
    cl = classifique(x[i],means,vs)
    predict = np.append(predict, cl)
accuracy = np.sum((predict==y) * 1)/l
print("accuracy : {}".format(accuracy))
cfmatrix = confusion_matrix(y, predict)
print("Matriz de confusion: \n{}".format(cfmatrix))

accuracy : 0.9333333333333333
Matriz de confusion: 
[[10  0  0]
 [ 0  8  2]
 [ 0  0 10]]
