### Knn aplicado a el conjunto Iris

Se aplicara el algortimo de clasificación knn al conjunto de datos
iris del repositorio de la UCI.

In [211]:
#Carga de bibliotecas
import numpy as np
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
from statistics import mode
data = load_iris().data
target = load_iris().target

In [243]:
ntest = 0.2
nclass = 3
ex_cl = 50

In [244]:
index = np.concatenate([np.arange(0, int((1-ntest)*ex_cl)), np.arange(ex_cl, ex_cl+int((1-ntest)*ex_cl)), np.arange(2*ex_cl, 2*ex_cl+int((1-ntest)*ex_cl))])
xtrain = np.array(data[index])
ytrain = target[index]
print("Conjunto de entrenamiento:\n {}\n".format(xtrain))

index = np.concatenate([np.arange(int((1-ntest)*ex_cl), ex_cl), np.arange(ex_cl+int((1-ntest)*ex_cl) , 2*ex_cl), np.arange(2*ex_cl+int((1-ntest)*ex_cl),3*ex_cl)])
xtest = np.array(data[index])
ytest = target[index]
print("Conjunto de prueba:\n {}\n".format(xtest))

Conjunto de entrenamiento:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5

In [245]:
print("Etiquetas del conjunto de entrenamiento: {}\n".format(ytrain))

print("Etiquetas del conjunto de prueba: {}\n".format(ytest))

Etiquetas del conjunto de entrenamiento: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]

Etiquetas del conjunto de prueba: [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]



In [249]:
def knn(x, train, target, k):
    d = pow((train - x),2) 
    d = np.sqrt(d.sum(axis=1))
    print(d)
    dt = np.array([[di, yi] for di, yi in zip(d, target)])
    return(np.sort(dt, axis=0)[0:k,:])

In [250]:
S = []
k = 11;
for i in range(0,xtest.shape[0]):
    d = knn(xtest[i], xtrain, ytrain, k)
    S = np.append(S,mode(d[:,1]))
msal = (S==ytest)*1
accuracy = msal.sum()/(nclass*ntest*ex_cl)
print("accuracy: {}".format(accuracy))

[0.17320508 0.52915026 0.43588989 0.60827625 0.17320508 0.7
 0.42426407 0.24494897 0.86023253 0.5        0.5        0.38729833
 0.58309519 0.90553851 0.9539392  1.161895   0.57445626 0.14142136
 0.86023253 0.37416574 0.58309519 0.31622777 0.51961524 0.5
 0.64807407 0.59160798 0.33166248 0.3        0.26457513 0.52915026
 0.54772256 0.46904158 0.69282032 0.87177979 0.5        0.33166248
 0.50990195 0.5        0.78740079 0.26457513 4.10609303 3.70540146
 4.2626283  3.1591138  3.88200979 3.49571166 3.8704005  2.38956063
 3.84837628 2.94108823 2.75317998 3.30302891 3.23573794 3.78681925
 2.64764046 3.72424489 3.50570963 3.1        3.84837628 2.95972972
 3.92428337 3.16069613 4.13400532 3.75099987 3.50998575 3.69188299
 4.14608249 4.33474336 3.61109402 2.57487864 2.88963666 2.77668868
 2.97489496 4.21544778 3.47706773 3.59722115 4.00624512 3.7067506
 3.07408523 3.08868904 5.35350353 4.27551167 5.39073279 4.7738873
 5.13419906 6.19193023 3.63455637 5.73585216 5.13711982 5.7210139
 4.43508737 